history.csv:
	wget https://github.com/glandfried/tennis_atp/releases/download/atp/history.csv.zip
	unzip history.csv.zip
	rm history.csv.zip

archive:
	wget https://github.com/glandfried/tennis/releases/download/data/kaggle-ATP-WTA-archive.zip
	unzip kaggle-ATP-WTA-archive.zip

